# Generated by Django 5.1.4 on 2024-12-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
