# Generated by Django 5.1.4 on 2024-12-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approval_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='snapshot',
            new_name='snapshot_config',
        ),
    ]
