# Generated by Django 5.1.4 on 2024-12-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_rename_snapshot_approval_snapshot_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('input', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='AgentWebhook',
        ),
    ]
