# Generated by Django 5.1.4 on 2024-12-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0011_remove_trigger_config_approval_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
